name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          uname -a
          sudo apt-key adv --keyserver keys.gnupg.net --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
          sudo add-apt-repository "deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic main" -u
          sudo apt install libwebp-dev librealsense2-dev libgtest-dev
          cd /usr/src/googletest
          sudo cmake .
          sudo cmake --build . --target install
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: Test
        run: build/tests
      - name: Create tarball for deployment
        run: |
          cp build/naminukas bin/naminukas
          tar -cvzf deploy.tgz bin
      - name: Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          curl -n -X POST https://api.heroku.com/apps/naminukas-demo/sources -H 'Accept: application/vnd.heroku+json; version=3' -H "Authorization: Bearer $HEROKU_API_KEY" > /tmp/urls.json
          curl "$(cat /tmp/urls.json | jq -r '.source_blob.put_url')" -X PUT -H 'Content-Type:' --data-binary @deploy.tgz
          curl -n -X POST https://api.heroku.com/apps/naminukas-demo/builds -d "{\"source_blob\":{\"url":\"$(cat /tmp/urls.json | jq -r '.source_blob.get_url')\"}}"" -H 'Accept: application/vnd.heroku+json; version=3' -H 'Content-Type: application/json' -H "Authorization: Bearer $HEROKU_API_KEY"
