name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          uname -a
          sudo apt-key adv --keyserver keys.gnupg.net --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
          sudo add-apt-repository "deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo bionic main" -u
          sudo apt install libwebp-dev librealsense2-dev libgtest-dev
          cd /usr/src/googletest
          sudo cmake .
          sudo cmake --build . --target install
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: Test
        run: build/tests
      # See https://devcenter.heroku.com/articles/platform-api-deploying-slugs
      - name: Create tarball for deployment
        run: |
          mkdir -p ./app
          cp build/naminukas app/naminukas
          tar czfv slug.tgz ./app
      - name: Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          curl -X POST -H 'Content-Type: application/json' -H 'Accept: application/vnd.heroku+json; version=3' -d '{"process_types":{"web":"./naminukas"}}' -n https://api.heroku.com/apps/naminukas-demo/slugs -H "Authorization: Bearer $HEROKU_API_KEY" > /tmp/response.json
          curl -X PUT -H 'Content-Type:' --data-binary @slug.tgz "$(cat /tmp/response.json | jq -r '.blob.url')"
          curl -X POST -H "Accept: application/vnd.heroku+json; version=3" -H "Content-Type: application/json" -d "{\"slug\":\"$(cat /tmp/response.json | jq -r '.id')\"}" -n https://api.heroku.com/apps/naminukas-demo/releases
